# api/config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        image:
            uri_prefix: /media/images
            upload_destination: '%kernel.project_dir%/public/media/images'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        dataCSV:
            uri_prefix: /media/CSV
            upload_destination: '%kernel.project_dir%/public/media/CSV'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer