/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 G.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
export default function Model(props) {
  const ref = useRef(null);

  useFrame(() =>{
    if(!ref.current){
      return;
    }
    ref.current.rotation.z += 0.01
  })
  const { nodes, materials } = useGLTF('/G.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.Text.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} scale={3} />
    </group>
  )
}

useGLTF.preload('/G.gltf')
